### ISSUE TITLE
Please use proper password hashing

### ISSUE THREAD

**Issue by PeeHaa** [ghalusa/PHP-Skeleton-App#1]
The password hashing used is `sha1` which really should never be used for hashing passwords.

https://github.com/ghalusa/PHP-Skeleton-App/blob/master/authenticate/models/authenticate.class.php#L69

Please fix this.

**Comment by ghalusa** [comment]
Hi Pieter. Thank you for your input. Your point is valid, and I do know better :) The system originated in an Active Directory environment. I admittedly cut a corner, and really shouldn't have. I'll have the fortified password hashing done, along with a salt, shortly.
