### ISSUE TITLE
No CSRF protection

### ISSUE THREAD

**Issue by PeeHaa** [ghalusa/PHP-Skeleton-App#2]
There seems to be no CSRF protection at all (unless I overlooked it) meaning  I can trick people into deleting / changing stuff. Like for example deleting users https://github.com/ghalusa/PHP-Skeleton-App/blob/master/user_account/models/user_account.class.php#L474

**Comment by ghalusa** [comment]
Hi Pieter. Another great point. I have it implemented in the other "Active Directory" based system. I'll have this implemented tonight or early tomorrow.

**Comment by ghalusa** [comment]
CSRF support has been implemented.

**Usage**

Place a reference to the "enforce_csrf_guard" function in a route like so:

```php
$app->post('/delete', "enforce_csrf_guard" ...
```

Include the "csrf_input.html" file, which contains the hidden input, in the target form:

```
{% include 'csrf_input.html' %}
```
