### ISSUE TITLE
Use of `global`s throughout the project

### ISSUE THREAD

**Issue by PeeHaa** [ghalusa/PHP-Skeleton-App#3]
There are a lot of places where `global`s are used making this project hard to debug, maintain and test. And as such a risk to use / build upon.

**Comment by ghalusa** [comment]
Hi Pieter. So true. I'll modify this shortly. Thanks!

**Comment by ghalusa** [comment]
Removed all global variables.

**CHANGES**

Set the variable in the autoload:

```php
$app->config('final_global_template_vars', $final_global_template_vars);
```

And set it where applicable:

```php
$final_global_template_vars = $app->config('final_global_template_vars');
```

**Comment by PeeHaa** [comment]
This solves nothing of the problems of using `global`s. The only thing this achieves is not using the `global` keyword, but the same issue are still there.

You have mutable global state:

    $app->config('final_global_template_vars', 'override - have fun debugging this');

There is no way to see whether for example the `authenticate_user()` uses some data / other dependencies to be able to do its work. Because by the looks of it (the function takes no parameters) it doesn't need anything to be able to do its work. However only when looking into the actual function it comes apparent that it actually needs a lot of stuff. In fact it apparently needs the entire application (`$app = \Slim\Slim::getInstance();`) in order for it to work. 

So yes you have removed the `global` keyword, but you just replaced it with global using a different technique which has the exact same problems.

**Comment by ghalusa** [comment]
So, you're saying I should feed everything it needs piece by piece? In this case, the authenticate_user() function needs:

```php
$final_global_template_vars["absolute_path_to_this_module"]
$final_global_template_vars["db_connection"]
$final_global_template_vars["session_key"]
$final_global_template_vars["auth_session_keys"]
$final_global_template_vars["session_key"]][$single_key]
```

I'm essentially going off of the Slim Framework's documentation on [route middleware](http://docs.slimframework.com/#Route-Middleware).

I see you folks are [having fun](http://chat.stackoverflow.com/transcript/11/2015/1/1/22-24) with this. I guess it goes with the territory. Thanks for the help, nonetheless. I do appreciate it.

**Comment by PeeHaa** [comment]
> So, you're saying I should feed everything it needs piece by piece?

Well I am not trying to tell you what you should do with your project. Just noting it will become a bit hard to maintain later. And for others to extend on it.

> I'm essentially going off of the Slim Framework's documentation on route middleware.

Fair enough

> I see you folks are having fun with this. I guess it goes with the territory.

/me looks at the chat backlog to see whether I said something waaay out of line again when I was drunk. Nope I was mild this time ;-)

> Thanks for the help, nonetheless. I do appreciate it.

No problem

**Comment by ghalusa** [comment]
Your observations are appreciated, and that's exactly why I placed the codebase out here, so I can get some feedback and grow. I was hoping for some knowledgable folks to come along and call me out on things, and that's exactly what you've done. I realize that if you didn't care, you wouldn't waste your time. So, thanks for contributing. It's priceless.
