### ISSUE TITLE
force_https checks doesn't correctly check whether the current request is indeed an https connection

### ISSUE THREAD

**Issue by PeeHaa** [ghalusa/PHP-Skeleton-App#4]
Some servers returned a non empty value even when the connection is not over https. So this check will fail: 
https://github.com/ghalusa/PHP-Skeleton-App/blob/master/vendor/default/functions/functions.php#L71

**Comment by ghalusa** [comment]
Pieter, thoughts?

https://github.com/ghalusa/PHP-Skeleton-App/blob/master/vendor/default/functions/functions.php#L71
